name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.compiler }} - Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
            
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Dependencies
      run: sudo apt-get install libxrandr-dev libxinerama-dev
      
    - name: Build
      run: ./build.sh
