name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.compiler }} - Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        compiler: [g++]
            
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Dependencies on Ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt-get update 
           sudo apt-get install xorg-dev
      
    - name: Build
      env:
        CC: ${{ matrix.compiler }}
      run: ./build.sh
