name: Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: ${{ matrix.conf.name }} - Build
    runs-on: ${{ matrix.conf.os }}
    strategy:
      fail-fast: false
      matrix:
        conf: [
          {
            name: "Ubuntu g++",
            os: ubuntu-latest,
            compiler: "g++"
          },{
            name: "Ubuntu clang++",
            os: ubuntu-latest,
            compiler: "clang++"
          }
        ]
            
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Dependencies on Ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt-get update 
           sudo apt-get install xorg-dev clang
      
    - name: Build
      env:
        CC: ${{matrix.conf.compiler}}
      run: ./build.sh
