name: Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Windows - Build
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: choco install cmake
      
      - name: Build
        run: ./build.sh