name: Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: ${{ matrix.conf.name }} - Build
    runs-on: ${{ matrix.conf.os }}
    strategy:
      fail-fast: false
      matrix:
        conf:
          - {
            name: "Windows Latest",
            os: windows-latest,
          }
            
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build
      run: |
        mkdir build
        cd build 
        cmake .. 
        cmake --build . 
